const propiedades = [
    {
      id: 1,
      imagen: '/img/as-prop/propiedades/001/casa.jose.01.jpg',
      direccion: 'Pte Peron 7693',
      barrio: 'Martin Coronado',
      tipo: 'Casa',
      valor: '170.000',
      vendido: false,
      etiquetas: ['4 amb.', 'patio', 'parrilla', 'garage', 'terraza libre'],
      descripcion: "Importante esquina con excelente cuidado. Cuenta con cocina amoblada, living comedor amplio con ventanales, baño completo, 2 habitaciones, patio con parrilla, garage y terraza libre.",
      zona: 'G.B.A Zona Oeste',
      carousel: [
        '../img/as-prop/propiedades/001/casa.jose.01.jpg',
        '../img/as-prop/propiedades/001/casa.jose.02.jpg',
        '../img/as-prop/propiedades/001/casa.jose.03.jpg',
        '../img/as-prop/propiedades/001/casa.jose.04.jpg',
        '../img/as-prop/propiedades/001/casa.jose.05.jpg',
        '../img/as-prop/propiedades/001/casa.jose.06.jpg',
        '../img/as-prop/propiedades/001/casa.jose.07.jpg',
      ],
    },
    {
      id: 2,
      imagen: '/img/as-prop/propiedades/002/dpto-villa-bosch.01.jpg',
      direccion: 'San Guillermo 5830',
      barrio: 'Villa Bosch',
      tipo: 'Dpto.',
      valor: '77.000',
      vendido: false,
      etiquetas: ['2 amb.', 'bañ.', 'placard', 'balcon'],
      descripcion: "Impecable y a estrenar dto 2 ambientes. Cuenta con cocina amoblada con bajo mesada, comedor amplio, baño totalmente equipado, habitación con placard embutido y balcón al frente.",
      zona: 'G.B.A Zona Oeste',
      carousel: [
        '../img/as-prop/propiedades/002/dpto-villa-bosch.01.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.02.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.03.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.04.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.05.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.06.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.07.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.08.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.09.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.10.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.11.jpg',
      ],
    },
    {
      id: 3,
      imagen: '/img/as-prop/propiedades/003/casa.palomar.01.jpg',
      direccion: 'Null',
      barrio: 'Palomar',
      tipo: 'Casa',
      valor: '200.000',
      vendido: false,
      etiquetas: ['3 amb.', '2 bañ.', 'cochera', 'pileta'],
      descripcion: "Impecable casa. Cuenta con pileta y cochera, amplia cocina y comedor.",
      zona: 'G.B.A Zona Oeste',
      carousel: [
        '../img/as-prop/propiedades/003/casa.palomar.01.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.02.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.03.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.04.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.05.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.06.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.07.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.08.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.09.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.10.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.11.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.12.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.13.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.14.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.15.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.16.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.17.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.18.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.19.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.20.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.21.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.22.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.23.jpg',
      ],
    },
    {
      id: 4,
      imagen: '/img/as-prop/propiedades/004/chalet.mcoronado.01.jpg',
      direccion: '12 de octubre 2141',
      barrio: 'Martin Coronado',
      tipo: 'Casa',
      valor: '290.000',
      vendido: false,
      etiquetas: ['3 dorm.', '2 bañ.', 'Parrilla', 'Jacuzzi', 'Jardin'],
      descripcion: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione culpa voluptate officia, qui doloribus vitae necessitatibus. Pariatur ipsum reprehenderit, dolore, alias architecto modi consequuntur, minima exercitationem accusantium quisquam quo soluta.",
      zona: 'G.B.A Zona Oeste',
      carousel: [
        '../img/as-prop/propiedades/004/chalet.mcoronado.01.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.02.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.03.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.04.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.05.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.06.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.07.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.08.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.09.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.10.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.20.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.21.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.22.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.23.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.24.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.25.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.26.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.27.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.28.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.29.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.30.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.30.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.31.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.32.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.33.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.34.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.35.jpg',
      ],
    },
    {
      id: 5,
      imagen: '../img/as-prop/propiedades/005/ciudad.jardin-lucas.01.jpg',
      direccion: 'NULL',
      barrio: 'Ciudad Jardin',
      tipo: 'Casa',
      valor: '290.000',
      vendido: true,
      etiquetas: [],
      descripcion: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione culpa voluptate officia, qui doloribus vitae necessitatibus. Pariatur ipsum reprehenderit, dolore, alias architecto modi consequuntur, minima exercitationem accusantium quisquam quo soluta.",
      zona: 'G.B.A Zona Oeste',
      carousel: [
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.01.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.02.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.03.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.04.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.05.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.06.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.07.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.08.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.09.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.10.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.20.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.21.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.22.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.23.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.24.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.25.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.26.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.27.jpg',
        '../img/as-prop/propiedades/005/ciudad.jardin-lucas.28.jpg',
      ],
    },
    {
      id: 6,
      imagen: '../img/as-prop/propiedades/006/dpto-ramos.01.jpg',
      direccion: 'Cangallo 500',
      barrio: 'Ramos Mejia',
      tipo: 'Dpto.',
      valor: '180.000',
      vendido: false,
      etiquetas: ['3 amb.', 'living', 'comedor', 'cocina', '2 dorm.','SUM'],
      descripcion: "Departamento de 3 ambientes ubicado en  Ramos Mejía a metros de Av de Mayo, muy luminoso, cuenta con living comedor, cocina dos dormitorios con placard, baño coompleto y balcón. El edificio cuenta con SUM (Salón de Usos Múltiples) con parrilla y Seguridad  las 24 hs.",
      zona: 'G.B.A Zona Oeste',
      mapa: src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3282.121998897094!2d-58.56618698412637!3d-34.6516217804471!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcc7dd10ae1305%3A0x879be672557ffdef!2sCangallo%20500%2C%20B1704FRL%20Ramos%20Mej%C3%ADa%2C%20Buenos%20Aires!5e0!3m2!1ses-419!2sar!4v1574441419657!5m2!1ses-419!2sar",
      carousel: [
        '../img/as-prop/propiedades/006/dpto-ramos.01.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.02.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.03.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.04.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.05.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.06.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.07.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.08.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.09.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.10.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.11.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.12.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.13.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.14.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.15.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.16.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.17.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.18.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.19.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.20.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.21.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.22.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.23.jpg',
        '../img/as-prop/propiedades/006/dpto-ramos.24.jpg',
      ],
    },
    {
      id: 7,
      imagen: '../img/as-prop/propiedades/007/san-martin-vend.01.jpg',
      direccion: 'San Lorenzo 2200',
      barrio: 'San Martin',
      tipo: 'Dpto.',
      valor: '290.000',
      vendido: true,
      etiquetas: ['64 m²', '3 amb.', 'cochera', 'apto credito'],
      descripcion: "2 dormitorios con placar, living comedor amplio, cocina comedor separada, baño, balcon y cochera, 64 mts2 estado muy bueno, edificio apto profesional, a una cuadra de la plaza san martin. APTO CREDITO BANCARIO!!. Las medidas indicadas son aproximadas y al solo efecto orientativo, las medidas reales surgirán del título de propiedad respectivo. La venta de este inmueble está sujeta a la tramitación del código de transferencia de inmuebles (COTI), de conformidad con la normativa vigente (Res. AFIP 2371/08, 2439/08 y ccs.), por parte de propietario. Fotos de carácter no contractual. El valor de las expensas, en caso de tener, está sujeto a verificación y/o ajustes.",
      zona: 'G.B.A Zona Norte',
      mapa: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3285.1034600352814!2d-58.54164728933679!3d-34.576248611477666!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcb7711c7954f1%3A0x38b6606cffae854a!2sSan%20Lorenzo%202200%2C%20B1650%20San%20Mart%C3%ADn%2C%20Buenos%20Aires!5e0!3m2!1ses-419!2sar!4v1574433678309!5m2!1ses-419!2sar",
      carousel: [
        '../img/as-prop/propiedades/007/san-martin-vend.01.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.02.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.03.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.04.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.05.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.06.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.07.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.08.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.09.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.10.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.11.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.12.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.13.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.14.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.15.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.16.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.17.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.18.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.19.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.20.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.21.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.22.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.23.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.24.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.25.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.26.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.27.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.28.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.29.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.30.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.31.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.32.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.33.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.34.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.35.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.36.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.37.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.38.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.39.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.40.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.41.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.42.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.43.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.44.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.45.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.46.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.47.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.48.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.49.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.50.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.51.jpg',
        '../img/as-prop/propiedades/007/san-martin-vend.52.jpg',
      ],
    },
]