const propiedades = [
    {
      id: 1,
      imagen: '/img/as-prop/propiedades/001/casa.jose.01.jpg',
      direccion: 'Pte Peron 7693',
      barrio: 'Martin Coronado',
      tipo: 'Casa',
      valor: '170.000',
      vendido: false,
      etiquetas: ['4 amb.', 'patio', 'parrilla', 'garage', 'terraza libre'],
      descripcion: "Importante esquina con excelente cuidado. Cuenta con cocina amoblada, living comedor amplio con ventanales, baño completo, 2 habitaciones, patio con parrilla, garage y terraza libre.",
      zona: 'G.B.A Zona Oeste',
      carousel: [
        '../img/as-prop/propiedades/001/casa.jose.01.jpg',
        '../img/as-prop/propiedades/001/casa.jose.02.jpg',
        '../img/as-prop/propiedades/001/casa.jose.03.jpg',
        '../img/as-prop/propiedades/001/casa.jose.04.jpg',
        '../img/as-prop/propiedades/001/casa.jose.05.jpg',
        '../img/as-prop/propiedades/001/casa.jose.06.jpg',
        '../img/as-prop/propiedades/001/casa.jose.07.jpg',
      ],
    },
    {
      id: 2,
      imagen: '/img/as-prop/propiedades/002/dpto-villa-bosch.01.jpg',
      direccion: 'San Guillermo 5830',
      barrio: 'Villa Bosch',
      tipo: 'Dpto.',
      valor: '77.000',
      vendido: false,
      etiquetas: ['2 amb.', 'bañ.', 'placard', 'balcon'],
      descripcion: "Impecable y a estrenar dto 2 ambientes. Cuenta con cocina amoblada con bajo mesada, comedor amplio, baño totalmente equipado, habitación con placard embutido y balcón al frente.",
      zona: 'G.B.A Zona Oeste',
      carousel: [
        '../img/as-prop/propiedades/002/dpto-villa-bosch.01.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.02.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.03.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.04.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.05.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.06.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.07.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.08.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.09.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.10.jpg',
        '../img/as-prop/propiedades/002/dpto-villa-bosch.11.jpg',
      ],
    },
    {
      id: 3,
      imagen: '/img/as-prop/propiedades/003/casa.palomar.01.jpg',
      direccion: 'Null',
      barrio: 'Palomar',
      tipo: 'Casa',
      valor: '200.000',
      vendido: false,
      etiquetas: ['3 amb.', '2 bañ.', 'cochera', 'pileta'],
      descripcion: "Impecable casa. Cuenta con pileta y cochera, amplia cocina y comedor.",
      zona: 'G.B.A Zona Oeste',
      carousel: [
        '../img/as-prop/propiedades/003/casa.palomar.01.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.02.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.03.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.04.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.05.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.06.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.07.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.08.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.09.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.10.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.11.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.12.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.13.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.14.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.15.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.16.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.17.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.18.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.19.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.20.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.21.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.22.jpg',
        '../img/as-prop/propiedades/003/casa.palomar.23.jpg',
      ],
    },
    {
      id: 4,
      imagen: '/img/as-prop/propiedades/004/chalet.mcoronado.01.jpg',
      direccion: '12 de octubre 2141',
      barrio: 'Martin Coronado',
      tipo: 'Casa',
      valor: '290.000',
      vendido: false,
      etiquetas: ['3 dorm.', '2 bañ.', 'Parrilla', 'Jacuzzi', 'Jardin'],
      descripcion: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione culpa voluptate officia, qui doloribus vitae necessitatibus. Pariatur ipsum reprehenderit, dolore, alias architecto modi consequuntur, minima exercitationem accusantium quisquam quo soluta.",
      zona: 'G.B.A Zona Oeste',
      carousel: [
        '../img/as-prop/propiedades/004/chalet.mcoronado.01.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.02.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.03.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.04.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.05.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.06.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.07.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.08.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.09.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.10.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.20.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.21.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.22.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.23.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.24.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.25.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.26.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.27.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.28.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.29.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.30.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.30.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.31.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.32.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.33.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.34.jpg',
        '../img/as-prop/propiedades/004/chalet.mcoronado.35.jpg',
      ],
    },
]